name: Check links

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.event.pull_request.number }}
          restore-keys: cache-lychee-${{ github.event.pull_request.number }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.4.0
        with:
          args: >-
            -v -n "*.md" "**/*.md" "**/*.mdx"
            --exclude "http://localhost*"
            --exclude "^https://logs-prod.*"
            --exclude ".*your-account.*"
            --exclude ".*qryn.local.*"
            --exclude "^https://d15jtxgb40qetw\\.cloudfront\\.net/.*"
            --exclude "https://github.com/odigos-io/ui-kit"
            --max-concurrency 5
            --retry-wait-time 10
            --max-retries 4
            --timeout 30
            --user-agent "Mozilla/5.0 (compatible; LycheeBot/2.0; +https://github.com/lycheeverse/lychee)"
            --cache --max-cache-age 1d
            --github-token ${{ secrets.GITHUB_TOKEN }}
          fail: true

      - name: Save lychee cache (only on cache miss)
        if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.event.pull_request.number }}
